api_platform:
    title: 'Remind Symfony API'
    description: 'The management API for Remind.'
    version: '0.0.1 nightly'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
